# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj ./bankingapi/
RUN dotnet restore -r linux-musl-x64 ./bankingapi/

# copy everything else and build app
COPY . ./bankingapi/
WORKDIR /source/bankingapi
RUN dotnet publish -c release -o /app -r linux-musl-x64 --self-contained true --no-restore /p:PublishTrimmed=true /p:PublishReadyToRun=true
