 
# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.csproj ./notpocapi/
RUN dotnet restore -r linux-musl-x64 ./notpocapi/

# copy everything else and build app
COPY . ./notpocapi/
WORKDIR /source/notpocapi
RUN dotnet publish -c release -o /app -r linux-musl-x64 --self-contained false

# final stage/image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine
WORKDIR /app
COPY --from=build /app ./

ENTRYPOINT ["./NotPocApi"]