### direct - deposit
POST http://localhost:5000/deposit HTTP/1.1
Content-Type: application/json

{ 
    "id": "17", 
    "amount": 12 
}

### direct - withdraw
POST http://localhost:5000/withdraw HTTP/1.1
Content-Type: application/json

{ 
    "id": "17", 
    "amount": 5 
}

### direct - balance
GET http://localhost:5000/17 HTTP/1.1

### dapr - withdraw

POST http://localhost:37318/v1.0/invoke/bankingapi/method/withdraw HTTP/1.1
Content-Type: application/json

{ 
    "id": "17", 
    "amount": 5 
}

### dapr - get

GET http://localhost:37318/v1.0/invoke/bankingapi/method/17 HTTP/1.1