### deposit
POST http://localhost:5000/account/deposit HTTP/1.1
Content-Type: application/json

{ 
    "id": "17", 
    "amount": 12 
}

### withdraw
POST http://localhost:5000/withdraw HTTP/1.1
Content-Type: application/json

{ 
    "id": "17", 
    "amount": 5 
}

### balance
GET http://localhost:5000/17 HTTP/1.1
